name: "Deploy"
on:
  push:
    tags:
      - '*.*.*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    container: ghcr.io/sitkoru/actions-container
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
      - name: Prepare
        id: prep
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Create packages
        run: dotnet pack -c Release /p:Version=${{ steps.prep.outputs.version }} -o packages
      - name: Publish nuget packages
        run: find packages -name *.nupkg -exec dotnet nuget push {} -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} \;
